a# yaml-language-server: $schema=./core-deployments.schema.json
---
description: Warp config for inEVMs native INJ warp route
timestamp: 2023-09-23T16:00:00.000Z
version:
  major: 1
  minor: 0
  patch: 0
data:
  # The list of chains to deploy ISMs onto
  chains:
    - name: injective
    - name: inevm
  
  config:
    - chainName: injective
      type: collateral
      address: inj
      ism: # TODO
      igp: # TODO
    - chainName: inevm
      type: native
      ism: # TODO
      igp: # TODO

  owner:
    injective: # multisig
    inevm: # multisig